sudo: false
dist: trusty
language: java

matrix:
  include:
# 8
  - env: JDK_RELEASE='OracleJDK 8'
    jdk: oraclejdk8
  - env: JDK_RELEASE='OpenJDK 8'
    jdk: openjdk8
# 9
  - env: JDK_RELEASE='OracleJDK 9'
    jdk: oraclejdk9
  - env: JDK_RELEASE='OpenJDK 9'
    install: . ./install-jdk.sh -F 9
# 10-ea
  - env: JDK_RELEASE='OracleJDK 10'
    install: . ./install-jdk.sh -F 10 -L BCL
  - env: JDK_RELEASE='OpenJDK 10'
    install: . ./install-jdk.sh -F 10 -L GPL
script:
  - java -version
  - cd unchained-build
  - mvn test -B
